services:
  app_db:
    image: 'postgres:16-alpine'
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: '${DB_USERNAME:-app_user}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-app_password}'
      POSTGRES_DB: '${DB_NAME:-app_db}'
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: 'no'

  qdrant_db:
    image: qdrant/qdrant:v1.18.1
    env_file:
      - .env.development
    environment:
      - QDRANT__SERVICE__API_KEY
      - QDRANT_LOG_LEVEL=${QDRANT_LOG_LEVEL:-INFO}
    ports:
      - 6333:6333
      - 6334:6334
    restart: 'no'
